# Generated by Django 4.1.5 on 2023-01-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='telegram_id',
        ),
    ]
